/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#1c110b',
        'surface-dim': '#1c110b',
        'surface-bright': '#45362f',
        'surface-container-lowest': '#170b07',
        'surface-container-low': '#251913',
        'surface-container': '#2a1d17',
        'surface-container-high': '#352721',
        'surface-container-highest': '#40312b',
        'on-surface': '#f6ddd4',
        'on-surface-variant': '#e0c0b2',
        'inverse-surface': '#f6ddd4',
        'inverse-on-surface': '#3c2d27',
        outline: '#a88a7e',
        'outline-variant': '#594238',
        'surface-tint': '#ffb595',
        primary: '#ffb595',
        'on-primary': '#571e00',
        'primary-container': '#ee671c',
        'on-primary-container': '#4c1a00',
        'inverse-primary': '#a23f00',
        secondary: '#bbcbb9',
        'on-secondary': '#263427',
        'secondary-container': '#3f4d3f',
        'on-secondary-container': '#adbdab',
        tertiary: '#adc6ff',
        'on-tertiary': '#002e69',
        'tertiary-container': '#4c8eff',
        'on-tertiary-container': '#00285c',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffdbcd',
        'primary-fixed-dim': '#ffb595',
        'on-primary-fixed': '#351000',
        'on-primary-fixed-variant': '#7c2e00',
        'secondary-fixed': '#d7e7d4',
        'secondary-fixed-dim': '#bbcbb9',
        'on-secondary-fixed': '#121e13',
        'on-secondary-fixed-variant': '#3c4a3d',
        'tertiary-fixed': '#d8e2ff',
        'tertiary-fixed-dim': '#adc6ff',
        'on-tertiary-fixed': '#001a41',
        'on-tertiary-fixed-variant': '#004494',
        background: '#1c110b',
        'on-background': '#f6ddd4',
        'surface-variant': '#40312b'
      },
      fontFamily: {
        'display': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-lg': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '1.3', letterSpacing: '-0.005em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '1.5', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '1.4', letterSpacing: '0.03em', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1.4', letterSpacing: '0.08em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      spacing: {
        unit: '4px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'panel-gap': '1px',
        'container-max': '1440px'
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px'
      },
      boxShadow: {
        'floating': '0 8px 32px rgba(0,0,0,0.4)',
      },
    },
  },
  plugins: [],
}
