/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed-variant": "#464747",
        "secondary-container": "#fed65b",
        "primary-container": "#1c1b1b",
        "on-tertiary-container": "#848484",
        "on-primary": "#ffffff",
        "outline-variant": "#c4c7c7",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-container": "#eeeeee",
        "outline": "#747878",
        "on-error": "#ffffff",
        "on-surface-variant": "#444748",
        "inverse-surface": "#2f3131",
        "tertiary": "#000000",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e2e2e2",
        "surface-container-low": "#f3f3f3",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c8c6c5",
        "primary": "#000000",
        "background": "#f9f9f9",
        "on-background": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ffe088",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary-container": "#745c00",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary-fixed-variant": "#574500",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-container": "#858383",
        "surface-tint": "#5f5e5e",
        "secondary": "#735c00",
        "surface-bright": "#f9f9f9",
        "tertiary-fixed-dim": "#c7c6c6",
        "error": "#ba1a1a",
        "surface-container-high": "#e8e8e8",
        "surface-variant": "#e2e2e2",
        "tertiary-container": "#1b1c1c",
        "surface-dim": "#dadada",
        "on-error-container": "#93000a",
        "primary-fixed": "#e5e2e1",
        "surface": "#f9f9f9",
        "inverse-primary": "#c8c6c5",
        "on-surface": "#1a1c1c",
        "on-primary-fixed-variant": "#474746",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#241a00",
        "tertiary-fixed": "#e3e2e2"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "unit": "4px",
        "lg": "24px",
        "gutter": "24px",
        "container-max": "1200px",
        "xs": "4px",
        "md": "16px",
        "xxl": "64px",
        "sm": "8px",
        "xl": "40px"
      },
      "fontFamily": {
        "code-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "code-md": ["14px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "30px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg-mobile": ["36px", { "lineHeight": "42px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "26px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "22px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
