apiVersion: v1
kind: Service
metadata:
  name: dataflow-frontend
  namespace: dataflow
spec:
  selector:
    app: dataflow-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
